/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AgentsIndexRouteImport } from './routes/agents.index'
import { Route as AgentsCodingRouteImport } from './routes/agents.coding'
import { Route as AgentsDeepfakeRouteImport } from './routes/agents.deepfake'
import { Route as AgentsDocumentationRouteImport } from './routes/agents.documentation'
import { Route as AgentsGeneralRouteImport } from './routes/agents.general'
import { Route as AgentsGraphRouteImport } from './routes/agents.graph'
import { Route as AgentsLegalRouteImport } from './routes/agents.legal'
import { Route as AgentsResearchRouteImport } from './routes/agents.research'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsCodingRoute = AgentsCodingRouteImport.update({
  id: '/agents/coding',
  path: '/agents/coding',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsDeepfakeRoute = AgentsDeepfakeRouteImport.update({
  id: '/agents/deepfake',
  path: '/agents/deepfake',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsDocumentationRoute = AgentsDocumentationRouteImport.update({
  id: '/agents/documentation',
  path: '/agents/documentation',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsGeneralRoute = AgentsGeneralRouteImport.update({
  id: '/agents/general',
  path: '/agents/general',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsGraphRoute = AgentsGraphRouteImport.update({
  id: '/agents/graph',
  path: '/agents/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsLegalRoute = AgentsLegalRouteImport.update({
  id: '/agents/legal',
  path: '/agents/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsResearchRoute = AgentsResearchRouteImport.update({
  id: '/agents/research',
  path: '/agents/research',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents/coding': typeof AgentsCodingRoute
  '/agents/deepfake': typeof AgentsDeepfakeRoute
  '/agents/documentation': typeof AgentsDocumentationRoute
  '/agents/general': typeof AgentsGeneralRoute
  '/agents/graph': typeof AgentsGraphRoute
  '/agents/legal': typeof AgentsLegalRoute
  '/agents/research': typeof AgentsResearchRoute
  '/agents/': typeof AgentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents/coding': typeof AgentsCodingRoute
  '/agents/deepfake': typeof AgentsDeepfakeRoute
  '/agents/documentation': typeof AgentsDocumentationRoute
  '/agents/general': typeof AgentsGeneralRoute
  '/agents/graph': typeof AgentsGraphRoute
  '/agents/legal': typeof AgentsLegalRoute
  '/agents/research': typeof AgentsResearchRoute
  '/agents': typeof AgentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents/coding': typeof AgentsCodingRoute
  '/agents/deepfake': typeof AgentsDeepfakeRoute
  '/agents/documentation': typeof AgentsDocumentationRoute
  '/agents/general': typeof AgentsGeneralRoute
  '/agents/graph': typeof AgentsGraphRoute
  '/agents/legal': typeof AgentsLegalRoute
  '/agents/research': typeof AgentsResearchRoute
  '/agents/': typeof AgentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/agents/coding'
    | '/agents/deepfake'
    | '/agents/documentation'
    | '/agents/general'
    | '/agents/graph'
    | '/agents/legal'
    | '/agents/research'
    | '/agents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/agents/coding'
    | '/agents/deepfake'
    | '/agents/documentation'
    | '/agents/general'
    | '/agents/graph'
    | '/agents/legal'
    | '/agents/research'
    | '/agents'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/agents/coding'
    | '/agents/deepfake'
    | '/agents/documentation'
    | '/agents/general'
    | '/agents/graph'
    | '/agents/legal'
    | '/agents/research'
    | '/agents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AgentsCodingRoute: typeof AgentsCodingRoute
  AgentsDeepfakeRoute: typeof AgentsDeepfakeRoute
  AgentsDocumentationRoute: typeof AgentsDocumentationRoute
  AgentsGeneralRoute: typeof AgentsGeneralRoute
  AgentsGraphRoute: typeof AgentsGraphRoute
  AgentsLegalRoute: typeof AgentsLegalRoute
  AgentsResearchRoute: typeof AgentsResearchRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/coding': {
      id: '/agents/coding'
      path: '/agents/coding'
      fullPath: '/agents/coding'
      preLoaderRoute: typeof AgentsCodingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/deepfake': {
      id: '/agents/deepfake'
      path: '/agents/deepfake'
      fullPath: '/agents/deepfake'
      preLoaderRoute: typeof AgentsDeepfakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/documentation': {
      id: '/agents/documentation'
      path: '/agents/documentation'
      fullPath: '/agents/documentation'
      preLoaderRoute: typeof AgentsDocumentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/general': {
      id: '/agents/general'
      path: '/agents/general'
      fullPath: '/agents/general'
      preLoaderRoute: typeof AgentsGeneralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/graph': {
      id: '/agents/graph'
      path: '/agents/graph'
      fullPath: '/agents/graph'
      preLoaderRoute: typeof AgentsGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/legal': {
      id: '/agents/legal'
      path: '/agents/legal'
      fullPath: '/agents/legal'
      preLoaderRoute: typeof AgentsLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/research': {
      id: '/agents/research'
      path: '/agents/research'
      fullPath: '/agents/research'
      preLoaderRoute: typeof AgentsResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AgentsCodingRoute: AgentsCodingRoute,
  AgentsDeepfakeRoute: AgentsDeepfakeRoute,
  AgentsDocumentationRoute: AgentsDocumentationRoute,
  AgentsGeneralRoute: AgentsGeneralRoute,
  AgentsGraphRoute: AgentsGraphRoute,
  AgentsLegalRoute: AgentsLegalRoute,
  AgentsResearchRoute: AgentsResearchRoute,
  AgentsIndexRoute: AgentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
